[package]
name = "branch"
version = "0.1.0"
authors = ["Kied Llaentenn <32681240+Kiedtl@users.noreply.github.com>"]
edition = "2018"

[dependencies]
gitignore = "1.0.6"
rayon = "1.2.0"
clap = "^2"
log = "0.4.8"
